//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks_Planner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TasksMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TasksMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tasks_Planner.Properties.TasksMessages", typeof(TasksMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректные данные. Пожалуйста, проверьте поля! Особенно обратите внимание на поле с датой! Минимальная дата должна быть на 30 минут больше текущей!.
        /// </summary>
        internal static string InvalidTaskData {
            get {
                return ResourceManager.GetString("InvalidTaskData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропущенных напоминаний не обнаружено!.
        /// </summary>
        internal static string MissedNotFound {
            get {
                return ResourceManager.GetString("MissedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропущенные периодичные напоминания!.
        /// </summary>
        internal static string MissedPeriodic {
            get {
                return ResourceManager.GetString("MissedPeriodic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропущенные напоминания!.
        /// </summary>
        internal static string MissedTasks {
            get {
                return ResourceManager.GetString("MissedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминание добавлено..
        /// </summary>
        internal static string TaskAdded {
            get {
                return ResourceManager.GetString("TaskAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминание уже существует..
        /// </summary>
        internal static string TaskExists {
            get {
                return ResourceManager.GetString("TaskExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминание с такими названием/описанием уже существует..
        /// </summary>
        internal static string TaskNotUnique {
            get {
                return ResourceManager.GetString("TaskNotUnique", resourceCulture);
            }
        }
    }
}
